### ISSUE TITLE
Impossible to uninstall

### ISSUE THREAD

**Issue by shark-oxi** [oliverkeeble/atom-language-assembly#1]
Hi,

Package is impossible to uninstall
```
Uninstalling “language-assembly” failed.Hide output…
Failed to delete language-assembly: Does not exist
```

Best regards,

**Comment by oliverkeeble** [comment]
I've noticed this in Atom, it seems to try uninstalling twice, failing the second time because it isn't there any more. It's a fairly recent thing. Try reloading Atom (Ctrl-Alt-R, or Cmd-Alt-Ctrl-L on Mac (I think)) and see if it's still in your package lists.

**Comment by oliverkeeble** [comment]
I've just had a look for this issue in the Atom repository, it's known: https://github.com/atom/atom/issues/11464

**Comment by shark-oxi** [comment]
Yeah it does the same with other package, just restart Atom and the package was effectively uninstalled.
