### ISSUE TITLE
package doesn't kick in or work?

### ISSUE THREAD

**Issue by gideondsouza** [oliverkeeble/atom-language-assembly#2]
So,

I just installed the package. I'm on Fedora 24 Atom 1.8.

I open a `file.s` and I don't see any syntax color! :/ What gives? I goto the packages section in the UI and I see `language-assembly` is installed?

**Comment by oliverkeeble** [comment]
How odd... It was all fine the last time I updated it. It's broken for me too :-(
I'll have a look and see what's happened.

**Comment by oliverkeeble** [comment]
OK, so everything seems to be working for me on Arch Linux and Mac, both on Atom 1.8.0. Could you run `atom --version` in a terminal and post the output please?

**Comment by gideondsouza** [comment]
Jeez. I just un installed, then reinstalled and everything is fine. I'm so sorry. I guess my brains were blocked and I must just assumed something is wrong the first time.

Sorry for the trouble.

**Comment by oliverkeeble** [comment]
No worries, it happens to all of us :-)
